### ISSUE TITLE
Data prep for bma() does not require sampling the posterior

### ISSUE THREAD

**Issue by drnickisaac** [robboyd/wrappeR#1]
@robboyd I was just discussing with @03rcooke about his work for the Scottish indicator.
He's been using your wrapper to run `bma()` on occupancy model outputs. He explained that the time-consuming step is the sample the posterior distribution, but in fact this is not necessary. `bma()` takes only a mean and standard deviation, not a vector describing the distribution: both these are stored already in the model outputs in the `BUGSoutput$mean` and `BUGSoutput$sd` slots.

NB `bma()` required data on the unbounded logit scale, so you should use the `a` parameter, not the `psi.fs`

**Comment by robboyd** [comment]
Excellent, very good to know. Will add an option to skip this step for bma

**Comment by drnickisaac** [comment]
Ok. I have written a new function `getA()` based on tempSampPost. The outputs are more-or-less comparable. So I think this deals with the issue for now.
