### ISSUE TITLE
running applySamp() on multiple taxa flips an error

### ISSUE THREAD

**Issue by drnickisaac** [robboyd/wrappeR#10]
It works fine with a single taxonomic group but not several.
I don't understand what `rbind.fill()` is doing.

**Comment by robboyd** [comment]
looks like applySamp returns a list of two dataframes whereas applyFilters just returns a data.frame. rbind.fill is the same as rbind but allows for unequal number of columns (with the mismatches set as NA). So you can't use rbind.fill on your applySamp while it returns a list of two dataframes

**Comment by drnickisaac** [comment]
It looks like to disaggregate in the way we need will require some quite major surgery. HELP!

**Comment by drnickisaac** [comment]
On reflection this is a desirable property. Let's keep it with a list of length equal to the number of taxonomic groups. That way we can apply the Clipping over each group separately, in parallel..
