### ISSUE TITLE
Errors from applyFilters when Region does not exist

### ISSUE THREAD

**Issue by drnickisaac** [robboyd/wrappeR#2]
Throws an error that is hard to identify initially. The only thing I'd changed from your code @robboyd  is to replace "GB" with "England". The help file says this is a valid option, but  actually it's stored in uppercase. So two changes are required:
1) edit the helpfile to specify that Region names should be uppercase
2) write a catch in `applyFilters()` to give a sensible error when the region names don't match the data on the object store.

**Comment by drnickisaac** [comment]
@robboyd does your recent update solve this problem?

**Comment by AugustT** [comment]
Lol, we solved this one a week ago! Sorry you had to go through this again @drnickisaac

**Comment by robboyd** [comment]
Ah yes sorry this slipped through the net. Have added a catch
