### ISSUE TITLE
wrappeR is corrupt

### ISSUE THREAD

**Issue by 03rcooke** [robboyd/wrappeR#26]
The current version of wrappeR returns no errors when installing. but if you try and use `createRoster()` it returns the error: 

> Error in get0(oNam, envir = ns) : lazy-load database '/data/notebooks/rstudio-recompile/scot/packrat/lib/x86_64-pc-linux-gnu/3.5.3/wrappeR/R/wrappeR.rdb' is corrupt

I checked this in a couple of projects to check it wasn't project specific.

I assume this happened after the latest merges?

@robboyd @AugustT @drnickisaac

**Comment by drnickisaac** [comment]
Is possible this is an issue with datalabs, or even packrat. I had the same error last week: I think it was for BRCindicators, not wrappeR. Either way, the error went away after I quit the R session and reloaded everything.

**Comment by 03rcooke** [comment]
Yep, must be a datalabs problem, I tried `remove.packages` and reinstalling but only restarting the session worked
