### ISSUE TITLE
Default roster to most recent runs

### ISSUE THREAD

**Issue by drnickisaac** [robboyd/wrappeR#7]
Mark has produced a spreadsheet with the path to the most recent model run. It would be really useful to use this lookup table as the default way to identify which `ver` to choose

**Comment by drnickisaac** [comment]
@roboke is going to look into how to read from the metadata spreadsheet

**Comment by 03rcooke** [comment]
I've added a pull request dealing with this. I've never built a package or issued a pull request before, so have a look and give it a check, I don't want to break anything!

**Comment by robboyd** [comment]
No worries will check it when I go back into datalabs later mate
